require:
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
